version: '3.8'

services:
  mysql-db:
    image: mysql:5.6
    container_name: retail-mysql
    volumes:
      - "mysql-data:/var/lib/mysql"  # Named volume for better management
      - "./sql-scripts:/docker-entrypoint-initdb.d"  # SQL scripts directory
    environment:
      MYSQL_DATABASE: retail_db
      MYSQL_USER: retail_user
      MYSQL_PASSWORD: itversity
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

volumes:
  mysql-data:  # Named volume persists data beyond container lifetime