services:
    db:
          image: mysql:5.6
          volumes:
            - "./.data/db:/var/lib/mysql"
          environment:
            - "MYSQL_DATABASE=retail_db"
            - "MYSQL_USER=retail_user"
            - "MYSQL_PASSWORD=itversity"
            - "MYSQL_ROOT_PASSWORD=root"
          ports:
              - "3307:3306"