services:
  mysql-db:
    image: mysql:5.6
    container_name: retail-mysql
    volumes:
      - "mysql-data:/var/lib/mysql"  # Named volume for better management
      - "./sql-scripts:/docker-entrypoint-initdb.d"  # SQL scripts directory
    environment:
      MYSQL_DATABASE: retail_db
      MYSQL_USER: $SOURCE_DB_USER
      MYSQL_PASSWORD: $SOURCE_DB_PASS
      MYSQL_ROOT_PASSWORD: $SOURCE_DB_ROOT_PASS
    ports:
      - "3307:3306"

volumes:
  mysql-data:  # Named volume persists data beyond container lifetime